url:
  michaelhartl: "https://www.michaelhartl.com"
  shim: "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
  learn_enought: "https://www.learnenough.com/"
  ruby_on_rails: "https://rubyonrails.org/"
  gravatar: "http://gravatar.com/emails"
  rails_tutorial:
    home: "https://www.railstutorial.org"
    news: "https://news.railstutorial.org/"
    screencast: "https://screencasts.railstutorial.org/"
    help: "http://www.railstutorial.org/help"
    contact: "https://www.railstutorial.org/contact"
    book: "https://www.railstutorial.org/book"

user:
  VALID_EMAIL_REGEX: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  NAME_MAX_LENGTH: 50
  EMAIL_MIN_LENGTH: 10
  EMAIL_MAX_LENGTH: 255
  PASSWORD_MIN_LENGTH: 6
  admin:
    USER_PER_PAGE: 15

email:
  TIME_EXPIRE_PASSWORD_RESET: 2

micropost:
  CONTENT_MAX_LENGTH: 140
  PER_PAGE: 15
  PICTURE_MAX_SIZE: 5
  ACCEPT_IMG_TYPE: "image/jpeg,image/gif,image/png"
  IMG_EXTENSION_ALLOW: <%= %w(jpg jpeg gif png) %>
  LIMIT_IMG_SIZE: [400, 400]

follow:
  USER_PER_PAGE: 15
